# Generated by Django 4.2.11 on 2024-04-29 05:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='default_country',
            field=django_countries.fields.CountryField(blank=True, max_length=56, null=True),
        ),
    ]
