# Generated by Django 4.2.11 on 2024-04-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userdetails_default_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='default_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
