# Generated by Django 4.2.11 on 2025-04-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdetails_default_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='default_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
