# Generated by Django 4.2.11 on 2024-04-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_service_services_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='sku',
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='services',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
