# Generated by Django 4.2.11 on 2024-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_casestudy_sku_services_sku_alter_casestudy_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
