# Generated by Django 4.2.11 on 2024-04-27 10:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_services_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
