# Generated by Django 4.2.11 on 2024-04-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='datasheet',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
