# Generated by Django 4.2.11 on 2024-04-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_datasheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='preferred_supplier',
            new_name='manufactured_by',
        ),
    ]
