# Generated by Django 4.2.11 on 2024-04-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newslettersignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='service_needed',
            field=models.CharField(blank=True, choices=[('Consulting', 'Consulting'), ('Project Management', 'Project Management'), ('Training', 'Training'), ('Design', 'Design'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
