# Generated by Django 4.2.11 on 2024-05-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_service_needed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSignUp',
        ),
    ]
