# Generated by Django 4.2.11 on 2025-04-21 10:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_whoweare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoweare',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
