# Generated by Django 4.2.11 on 2025-04-21 10:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_whoweare_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoweare',
            name='about_kevin',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
