# Generated by Django 4.2.11 on 2024-04-28 18:41

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0004_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to='users.userdetails'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=56),
        ),
    ]
